countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea, North",
    "Korea, South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]

big_cities = [
    "Tokyo",
    "New York City",
    "London",
    "Paris",
    "Beijing",
    "Moscow",
    "Cairo",
    "Rio de Janeiro",
    "Sydney",
    "Toronto",
    "Berlin",
    "Rome",
    "Bangkok",
    "Dubai",
    "Mumbai",
    "Los Angeles",
    "Istanbul",
    "Seoul",
    "Mexico City",
    "Cape Town",
    "Jakarta",
    "Madrid",
    "Buenos Aires",
    "Lima",
    "Nairobi",
    "Amsterdam",
    "Stockholm",
    "New Delhi",
    "Vienna",
    "Athens",
    "Prague",
    "Budapest",
    "Hong Kong",
    "Singapore",
    "Kuala Lumpur",
    "Oslo",
    "Copenhagen",
    "Warsaw",
    "Zurich",
    "Helsinki",
    "Dublin",
    "Lisbon",
    "Brussels",
    "Riyadh",
    "Doha",
    "Manila",
    "Hanoi",
    "Brasília",
    "Ottawa",
    "Havana",
    "Bogotá",
    "Caracas",
    "Santiago",
    "Montevideo",
    "Ljubljana",
    "Reykjavik",
    "Panama City",
    "San Juan",
    "Bucharest",
    "Kiev",
    "Tehran",
    "Baghdad",
    "Damascus",
    "Kabul",
    "Islamabad",
    "Kathmandu",
    "Dhaka",
    "Colombo",
    "Nicosia",
    "Vilnius",
    "Tallinn",
    "Belgrade",
    "Tirana",
    "Tbilisi",
    "Yerevan",
    "Baku",
    "Ashgabat",
    "Astana",
    "Ulaanbaatar",
    "Bishkek",
    "Tashkent",
    "Kuala Lumpur",
    "Manama",
    "Muscat",
    "Abu Dhabi",
    "Doha",
    "Nur-Sultan",
    "Bogota",
    "Quito",
    "La Paz",
    "Asuncion",
    "Paramaribo",
    "Georgetown",
    "Bridgetown",
    "Nassau",
    "Kingston",
    "Port-au-Prince",
    "San Salvador",
    "Guatemala City",
    "Belmopan",
    "Tegucigalpa",
    "Managua",
    "San Jose",
    "Panama City",
    "Lima",
    "Caracas",
    "Buenos Aires",
    "Montevideo",
    "Santiago",
    "Brasilia",
    "La Paz",
    "Sucre",
    "Quito",
    "Paramaribo",
    "Georgetown",
    "Bridgetown",
    "Nassau",
    "Kingston",
    "Port-au-Prince",
    "San Salvador",
    "Guatemala City",
    "Belmopan",
    "Tegucigalpa",
    "Managua",
    "San Jose",
]

monsters = [
    "A happy fluffy monster",
    "Two happy fluffy monsters",
    "Three happy fluffy monsters",
]
