import random

regions = [
    "Alaska",
    "Andalusia",
    "Bavaria",
    "British Columbia",
    "Catalonia",
    "Corsica",
    "Dalmatia",
    "Flanders",
    "Galicia",
    "Hokkaido",
    "Istria",
    "Jutland",
    "Karelia",
    "Labrador",
    "Maghreb",
    "Normandy",
    "Occitania",
    "Patagonia",
    "Queensland",
    "Sardinia",
    "Tasmania",
    "Umbria",
    "Valais",
    "Wales",
    "Xinjiang",
    "Yorkshire",
    "Zanzibar",
    "Amazonas",
    "Bengal",
    "Calabria",
    "Dagestan",
    "Emilia-Romagna",
    "Fujian",
    "Guangxi",
    "Hokkaido",
    "Ile-de-France",
    "Jalisco",
    "Kashmir",
    "Lazio",
    "Madhya Pradesh",
    "Nevada",
    "Ontario",
    "Punjab",
    "Qinghai",
    "Rajasthan",
    "Sicily",
    "Tuscany",
    "Ulster",
    "Valencia",
    "Western Cape",
    "Xiamen",
    "Yunnan",
    "Zamboanga",
    "Abruzzo",
    "Baja California",
    "Canton",
    "Dalarna",
    "Eastern Cape",
    "Faroe Islands",
    "Goa",
    "Hebei",
    "Iceland",
    "Jiangxi",
    "Karnataka",
    "Lombardy",
    "Maine",
    "Norrland",
    "Okinawa",
    "Piedmont",
    "Queensland",
    "Rhineland",
    "Saxony",
    "Thuringia",
    "Uttar Pradesh",
    "Victoria",
    "Wallonia",
    "Xinjiang",
    "Yukon",
    "Zealand",
    "Amhara",
    "Brittany",
    "Chiapas",
    "Dorset",
    "East Java",
    "Friuli",
    "Galilee",
    "Hainan",
    "Inner Mongolia",
    "Java",
    "Kerala",
    "Lapland",
    "Murcia",
    "New South Wales",
    "Orkney",
    "Puglia",
    "Quito",
    "Rhodes",
    "Sumatra",
    "Transylvania",
]

countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea, North",
    "Korea, South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
]

big_cities = [
    "Tokyo",
    "New York City",
    "London",
    "Paris",
    "Beijing",
    "Moscow",
    "Cairo",
    "Rio de Janeiro",
    "Sydney",
    "Toronto",
    "Berlin",
    "Rome",
    "Bangkok",
    "Dubai",
    "Mumbai",
    "Los Angeles",
    "Istanbul",
    "Seoul",
    "Mexico City",
    "Cape Town",
    "Jakarta",
    "Madrid",
    "Buenos Aires",
    "Lima",
    "Nairobi",
    "Amsterdam",
    "Stockholm",
    "New Delhi",
    "Vienna",
    "Athens",
    "Prague",
    "Budapest",
    "Hong Kong",
    "Singapore",
    "Kuala Lumpur",
    "Oslo",
    "Copenhagen",
    "Warsaw",
    "Zurich",
    "Helsinki",
    "Dublin",
    "Lisbon",
    "Brussels",
    "Riyadh",
    "Doha",
    "Manila",
    "Hanoi",
    "Brasília",
    "Ottawa",
    "Havana",
    "Bogotá",
    "Caracas",
    "Santiago",
    "Montevideo",
    "Ljubljana",
    "Reykjavik",
    "Panama City",
    "San Juan",
    "Bucharest",
    "Kiev",
    "Tehran",
    "Baghdad",
    "Damascus",
    "Kabul",
    "Islamabad",
    "Kathmandu",
    "Dhaka",
    "Colombo",
    "Nicosia",
    "Vilnius",
    "Tallinn",
    "Belgrade",
    "Tirana",
    "Tbilisi",
    "Yerevan",
    "Baku",
    "Ashgabat",
    "Astana",
    "Ulaanbaatar",
    "Bishkek",
    "Tashkent",
    "Kuala Lumpur",
    "Manama",
    "Muscat",
    "Abu Dhabi",
    "Doha",
    "Nur-Sultan",
    "Bogota",
    "Quito",
    "La Paz",
    "Asuncion",
    "Paramaribo",
    "Georgetown",
    "Bridgetown",
    "Nassau",
    "Kingston",
    "Port-au-Prince",
    "San Salvador",
    "Guatemala City",
    "Belmopan",
    "Tegucigalpa",
    "Managua",
    "San Jose",
    "Panama City",
    "Lima",
    "Caracas",
    "Buenos Aires",
    "Montevideo",
    "Santiago",
    "Brasilia",
    "La Paz",
    "Sucre",
    "Quito",
    "Paramaribo",
    "Georgetown",
    "Bridgetown",
    "Nassau",
    "Kingston",
    "Port-au-Prince",
    "San Salvador",
    "Guatemala City",
    "Belmopan",
    "Tegucigalpa",
    "Managua",
    "San Jose",
]

indoor_places = [
    "Living room",
    "Kitchen",
    "Bedroom",
    "Bathroom",
    "Dining room",
    "Home office",
    "Laundry room",
    "Garage",
    "Basement",
    "Attic",
    "Closet",
    "Pantry",
    "Library",
    "Gym",
    "Lobby",
    "Conference room",
    "Classroom",
    "Auditorium",
    "Laboratory",
    "Waiting room",
    "Hallway",
    "Atrium",
    "Gymnasium",
    "Locker room",
    "Sauna",
    "Steam room",
    "Indoor pool",
    "Game room",
    "Theater",
    "Cinema",
    "Cafeteria",
    "Restaurant",
    "Bar",
    "Cafe",
    "Bakery",
    "Butcher shop",
    "Grocery store",
    "Shopping mall",
    "Bookstore",
    "Toy store",
    "Electronics store",
    "Pharmacy",
    "Hospital room",
    "Operating room",
    "Emergency room",
    "Doctor's office",
    "Dentist's office",
    "Veterinary clinic",
    "Laboratory",
    "Research lab",
    "Data center",
    "Server room",
    "Bank vault",
    "Classroom",
    "Lecture hall",
    "Museum",
    "Art gallery",
    "Exhibition hall",
    "Greenhouse",
    "Indoor garden",
    "Zoo exhibit",
    "Aquarium",
    "Library reading room",
    "Study room",
    "Music room",
    "Dance studio",
    "Recording studio",
    "Broadcast studio",
    "TV studio",
    "Radio station",
    "Newsroom",
    "Press room",
    "Control room",
    "War room",
    "Situation room",
    "Bunker",
    "Wine cellar",
    "Cigar lounge",
    "Spa",
    "Massage room",
    "Beauty salon",
    "Hair salon",
    "Nail salon",
    "Tattoo parlor",
    "Piercing studio",
    "Photography studio",
    "Printing press",
    "Factory floor",
    "Workshop",
    "Laboratory",
    "Clean room",
    "Warehouse",
    "Distribution center",
    "Stockroom",
    "Showroom",
    "Sales floor",
    "Waiting area",
    "Reception",
    "Office cubicle",
    "Meeting room",
    "Boardroom",
    "Break room",
]

outdoor_places = [
    "Park",
    "Beach",
    "Forest",
    "Mountain",
    "Desert",
    "Lake",
    "River",
    "Waterfall",
    "Meadow",
    "Canyon",
    "Valley",
    "Cliff",
    "Prairie",
    "Swamp",
    "Wetland",
    "Garden",
    "Orchard",
    "Vineyard",
    "Farm",
    "Field",
    "Pasture",
    "Pond",
    "Marsh",
    "Hiking trail",
    "Nature reserve",
    "Wildlife sanctuary",
    "National park",
    "State park",
    "Amusement park",
    "Playground",
    "Zoo",
    "Botanical garden",
    "Arboretum",
    "Golf course",
    "Sports field",
    "Stadium",
    "Open-air market",
    "Farmer's market",
    "Flea market",
    "Street market",
    "Plaza",
    "Town square",
    "Courtyard",
    "Patio",
    "Backyard",
    "Terrace",
    "Rooftop",
    "Balcony",
    "Veranda",
    "Promenade",
    "Boardwalk",
    "Pier",
    "Harbor",
    "Port",
    "Dock",
    "Marina",
    "Beachfront",
    "Seashore",
    "Coastline",
    "Bay",
    "Peninsula",
    "Island",
    "Peninsula",
    "Reef",
    "Cave",
    "Gorge",
    "Glacier",
    "Iceberg",
    "Tundra",
    "Savanna",
    "Rainforest",
    "Jungle",
    "Campsite",
    "Campground",
    "RV park",
    "Picnic area",
    "Scenic overlook",
    "Vista point",
    "Lookout tower",
    "Observation deck",
    "Scenic byway",
    "Country road",
    "Bike path",
    "Walking path",
    "Bridge",
    "Dam",
    "Reservoir",
    "Quarry",
    "Mine",
    "Wind farm",
    "Solar farm",
    "Fishing spot",
    "Hunting ground",
    "Birdwatching site",
    "Hot spring",
    "Geyser",
    "Volcano",
    "Lighthouse",
    "Ruins",
    "Archaeological site",
    "Monument",
    "Statue",
    "Historic battlefield",
    "Historic site",
    "Outdoor amphitheater",
]

monsters = [
    "A happy fluffy monster",
    "Two happy fluffy monsters",
    "Three happy fluffy monsters",
]


def random_location():
    match random.randint(1, 4):
        case 1:
            return random.choice(regions)
        case 2:
            return random.choice(big_cities)
        case 3:
            return random.choice(indoor_places)
        case 4:
            return random.choice(outdoor_places)


def random_monster():
    return random.choice(monsters)
